export const ADD_PRODUCT_CART = 'CART/ADD_PRODUCT_CART'
export const REMOVE_PRODUCT_CART = 'CART/REMOVE_PRODUCT_CART'
export const CLEAR_PRODUCTS_CART = 'CART/CLEAR_PRODUCTS_CART'
export const UPDATE_COUNT_PRODUCT_CART = 'CART/UPDATE_COUNT_PRODUCT_CART'

export const SET_PRODUCT_LIST = 'PRODUCT/SET_PRODUCT_LIST'
